app/urls.py
from django.conf.urls import url
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.views import login, logout
from app.views import send_morsel, start_hunt, MorselList, MorselDetailView,\
register, create_morsel, HomePageView, FAQPageView, AboutPageView,\
newsletter_signup, edit_morsel, morsel_list_public

app_name = 'app'
urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^morsels/$', MorselList.as_view(), name='morsel_list'),
    url(r'^morsels_public/$', morsel_list_public, name='morsel_list_public'),
    url(r'^morsels/send/$', send_morsel, name='morsel_send'),
    url(r'^morsels/(?P<morsel_id>[0-9]+)/start_hunt/$', start_hunt, name='start_hunt'),
    url(r'^register/', register, name='register'),
    url(r'^faq/$', FAQPageView.as_view(), name='faq'),
    url(r'^about/$', AboutPageView.as_view(), name='about'),
    url(r'^morsels/create/$', create_morsel, name="create_morsel"),
    url(r'^morsels/(?P<morsel_id>[0-9]+)/edit/$', edit_morsel, name='edit_morsel'),
    url(r'^morsels/(?P<pk>[0-9]+)/display/$', MorselDetailView.as_view(), name='morsel_detail'),
    url(r'^newsletter_signup/$', newsletter_signup, name='newsletter_signup')
]

morsels/urls.py
from django.shortcuts import redirect
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
import debug_toolbar

app_name = 'morsels'
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/', include('app.urls'), name='app'),
    url(r'^$', lambda r: redirect('/app/'), name='root-redirect'),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^login/$', auth_views.login),
    url(r'^logout/$', auth_views.logout)
]

app/templates/app/about.html
{% extends "app/base.html" %}
{% load static %}

{% block content %}
    <div class="py-5 bg-white">
        <div class="container">
            <div class="row">
            <div class="col-md-12">
                <h3>About Us</h3>
                <p>Crumbly was created with the vision of building a robust, scalable platform that allows
                    for the creation of simple SMS-based treasure hunts. 
                </p>
                <p>
                    We aim to iterate and improve on this product as often as possible. Feel free to contact us with 
                    feedback at <strong>support@getcrumbly.com</strong>. 
                </p>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/base.html
{% load static %}
<html><head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
        <!-- Custom links -->
        <link href="{% static 'app/css/style.css' %}" rel="stylesheet" type="text/css" />
        <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-success">
          <div class="container">
            <a class="navbar-brand" href="/"><img src="{% static 'app/images/logo.png' %}"></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
            <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
              <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'app:morsel_list' %}">My Morsels</a>
                    </li>  
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'app:morsel_list_public' %}">Public Morsels</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'app:about' %}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'app:faq' %}">FAQ</a>
                </li>
              </ul>
              {% if user.is_authenticated %}
                 <a href="/logout" class="btn navbar-btn ml-2 btn-light text-success">Logout</a>
              {% else %}
                 <a href="/login"class="btn navbar-btn ml-2 btn-light text-success">Login/Signup</a>
              {% endif %}
            </div>
          </div>
        </nav>
        {% block content %}
        {% endblock %}
        <div class="py-5 text-white bg-success">
          <div class="container">
            <div class="row">
              <div class="col-md-9">
                {% if not request.session.newsletter_signed_up %}
                <p class="lead">Enter your email for the scoop on the latest Crumbs!</p>
                <form action="{% url 'app:newsletter_signup' %}" method="post" class="form-inline">
                  {% csrf_token %}  
                  <div class="form-group">
                    <input name="email" type="email" class="form-control" placeholder="Your e-mail here"> </div>
                  <button type="submit" class="btn btn-primary ml-3">Subscribe</button>
                </form>
                {% endif %}
                <p class="">Need help? Shoot us an email at <a href="mailto:support@getcrumbly.com"><strong class="text-white">support@getcrumbly.com</strong></a></p>   
              </div>
              <div class="col-4 col-md-1 align-self-center">
                <a href="https://twitter.com" target="_blank"><i class="fa fa-fw fa-twitter fa-3x text-white"></i></a>
              </div>
              <div class="col-4 col-md-1 align-self-center">
                <a href="https://www.instagram.com" target="_blank"><i class="fa fa-fw fa-instagram text-white fa-3x"></i></a>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 mt-3 text-center">
                <p> © Copyright 2017 Crumbly - All rights reserved.</p>
                <p> Built with ❤ in Portland by a ragtag group of devs and marketers.</p>
                <a href="http://www.djangoproject.com/"><img src="https://www.djangoproject.com/m/img/badges/djangoproject120x25.gif" border="0" alt="A Django project." title="A Django project." /></a>
              </div>
            </div>
          </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
      
      
      </body></html>

app/templates/app/create_morsel.html
{% extends "app/base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {{ formset.management_form }}
        <table>
            {% for form in formset %}
                {{ form }}
            {% endfor %}
            <input type="submit" name="action" value="+">
        </table>
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Create!
            </button>
        {% endbuttons %}
    </form>
</div>    
{% endblock %}

app/templates/app/edit_morsel.html
{% extends "app/base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {{ formset.management_form }}
        <table>
            {% for form in formset %}
                {{ form }}
            {% endfor %}
        </table>
        <input type="submit" name="action" value="+">
        <input type="submit" name="action" value="-">
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Save Changes
            </button>
            <a href="/app/morsels"class="btn ml-2 btn-primary text-white">Go Back</a>
        {% endbuttons %}
    </form>
</div>    
{% endblock %}

app/templates/app/faq.html
{% extends "app/base.html" %}
{% load static %}

{% block content %}
<div class="py-5 bg-white">
    <div class="container" >
        
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                Our FAQ aims to help answer common questions related to <strong>Crumbly</strong>. If you cannot find an answer to your question, 
                make sure to contact us. 
            </div>

            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="row">
                        <div class="col-md-12">
                            <h3> General </h3>
                            <p><strong> Is account registration required? </strong></p>
                            <p>Account registration at <strong>Crumbly</strong> is required only if you want to create and manage Crumbs. 
                                No account is necessary to play.</p>
                            <p><strong> What is a Crumb? </strong></p>
                            <p> A Crumb is a SMS-based treasure hunt. </p>
                            <p><strong> What is a Crumb? </strong></p>
                            <p> A Crumb is a SMS-based treasure hunt. </p>
                            <p><strong> Do I need to pay to use Crumbly? </strong></p>
                            <p> For now, we are keeping things free. Over time, we plan to incoporporate paid plans 
                                so we can sustainably grow.
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h3> For Creators </h3>
                            <p><strong> How do I create a new Crumb? </strong></p>
                            <p>Follow these steps:
                                <ol>
                                    <li> Login or Signup to get access</li>
                                    <li> Click on My Crumbs to view list of crumbs you have created </li>
                                    <li> Click on Create to pull up form for creating new Crumbs </li>
                                </ol>
                            </p>
                            <p><strong>Do I have to set a start and end time for each Crumb?</strong></p>
                            <p> No, you do not require a start and end time for each crumb. If you leave these fields blank,
                                then your treasure hunt will remain active indefinitely
                            </p>
                            <p><strong>Can I create image clues?</strong></p>
                            <p>Not yet. This is an upcoming feature. Stay tuned.</p>
                            <p><strong>What about engagement metrics?</strong></p>
                            <p>This feature will be coming soon.</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <p><strong>How do I join a Crumb?</strong></p>   
                            <p>Follow these steps:
                                <ul>
                                    <li><strong>With a Crumb Code: </strong> If you have a Crumb Code, text "crumb <join code>" to +1-(201)-730-4915  </li>
                                        
                                    <li><strong>Via email:</strong> You might be invited to a Crumb via email. Click the link and follow instructions</li>
                                </ul>
                            </p> 
                            <p><strong>How can I find more Crumbs?</strong></p>
                            <p>Look out for Crumb codes at local retailers, coffee shops. Sometimes we hide them on Craigslists
                                Other times they might be stuck to a telephone post. </p>
                                    <p> We will be releasing a list of publicly avaialble Crumbs shortly! </p></p>
                        </div>
                    </div>
                </div>
            </div>
            
    </div>
</div>
            
    
{% endblock %}

app/templates/app/home.html
{% extends "app/base.html" %}
{% load static %}
{% block content %}
<div class="pt-5 bg-light text-dark" style="background-image:url('/static/app/images/n-120570.jpg'); -webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;">
        <div class="container">
          <div class="row">
            <div class="col-md-6 text-md-left text-center align-self-center my-5" style="">
              <h1 class="display-1" style="color:white">SMS Treasure Hunts</h1>
              <p class="lead" style="color:white">Simple. Download-free. Easy setup.</p>
              <div class="row mt-5">
                {% if not user.is_authenticated %}
                    <div class="col-md-5 col-6">
                        <a href="/login"class="btn ml-2 btn-primary text-white">Get Started</a>
                    </div>
                {% endif %}
              </div>
            </div>
            <div class="col-md-6" style="">
              <img class="img-fluid d-block max-width:100% height:auto mx-auto" src="{% static 'app/images/message-ios.png' %}"> </div>
          </div>
        </div>
      </div>
      <div class="py-5" style="background:#FD971F">
        <div class="container">
          <div class="row text-white">
            <div class="py-5 col-md-6">
              <div class="row">
                <div class="text-center col-4"><i class="d-block mx-auto fa fa-5x fa-angle-double-up"></i></div>
                <div class="col-8">
                  <h5 class="mb-3 text-primary"><b class="text-white">Robust Architecture</b></h5>
                  <p class="my-1">SMS is a tried and tested protocol for mass communication. We stand on the shoulder of a robust network and can scale with ease.</p>
                </div>
              </div>
            </div>
            <div class="py-5 col-md-6">
              <div class="row">
                <div class="text-center col-4"><i class="d-block mx-auto fa fa-5x fa-map-o"></i></div>
                <div class="col-8" style="">
                  <h5 class="mb-3 text-primary"><b class="text-white">Engage</b></h5>
                  <p class="my-1">Use our reports to measure key KPIs like response rates and time between responses. Create loops within hunts. Trigger email campaigns and more</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="py-5 col-md-6 text-white">
              <div class="row">
                <div class="text-center col-4"><i class="d-block mx-auto fa fa-5x fa-file-o"></i></div>
                <div class="col-8">
                  <h5 class="mb-3 text-primary"><b class="text-white">Create</b></h5>
                  <p class="my-1">Build with blocks, yet modify easily. Customization is one click away and the graphic possibilities are infinite. </p>
                </div>
              </div>
            </div>
            <div class="py-5 col-md-6 text-white">
              <div class="row">
                <div class="text-center col-4"><i class="d-block mx-auto fa fa-5x fa-money"></i></div>
                <div class="col-8">
                  <h5 class="mb-3 text-white"><b>Inexpensive</b></h5>
                  <p class="my-1">Customize your experience with our inexpensive pay-per-hunt plans or subscribe for increased scalability. Your&nbsp;</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

app/templates/app/morsel_detail.html
{% extends "app/base.html" %}
{% block content %}
    <h1>{{ object.name }}</h1>
    <p> {{object.welcome_text }}</p>
    <ul>
        {%for question in object.questions.all %}
            <li> {{ question.question_text }}
                <ul><li>{{ question.answer.answer_text }}</li></ul>
            </li>
        {% endfor %}
    </ul>
    <p> {{ object.completed_text }}</p>
{% endblock %}

app/templates/app/morsel_list.html
{% extends "app/base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% block content %}
    
    <div class="row">
        <div class="col-md-8 col-offset-md-2">
                <h2>My Morsels</h2>
                {% if user.is_authenticated %}
                    <p>Hello! Welcome <strong>{{ user.username }}</strong></p>
                {% endif %}
                <table>
                    <thead>
                        <th>Crumb Name</th>
                    </thead>
                    {% for morsel in object_list %}
                    <tr>
                        <td>{{ morsel.name }}</td>
                        <td class="active"><a class="btn btn-primary" href="{%url 'app:morsel_detail' morsel.id%}">View</a> </td>    
                        <td><a class="btn btn-primary" href="{%url 'app:edit_morsel' morsel.id %}">Edit</a></td>
                        <td><a class="btn btn-primary" href="{%url 'app:start_hunt' morsel.id%}">Send!</a></td>
                    </tr>
                    {% endfor %}
                </table>
        </div>
    </div> 
    {% if messages %}
        {% for msg in messages %}       
            {% bootstrap_alert msg.message alert_type=msg.level_tag %}
        {% endfor %}
    {% endif %}
{% endblock %}

app/templates/app/morsel_list_public.html
{% extends "app/base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% block content %}
    <h2>Public Crumbles</h2>
    <div class="row">
        <div class="col-md-8 col-offset-md-2">
            <p> This is a list of all public Crumbles. </p>
            <table>
                <thead>
                    <th>Crumb Name</th>
                    <th>Description</th>
                </thead>
                {% for morsel in morsels %}
                <tr>
                    <td>{{ morsel.name }}</td>
                    <td>{{ morsel.welcome_text }}</td>
                    <td><a class="btn btn-primary" href="{%url 'app:start_hunt' morsel.id%}">Send!</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    
    {% if messages %}
        {% for msg in messages %}       
            {% bootstrap_alert msg.message alert_type=msg.level_tag %}
        {% endfor %}
    {% endif %}
{% endblock %}

app/templates/app/register.html
{% extends "app/base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Create!
            </button>
        {% endbuttons %}
    </form>
</div>    
{% endblock %}